# Generated by Django 3.1.6 on 2021-08-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210306_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Name'),
        ),
    ]
