# Generated by Django 3.1.6 on 2021-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210810_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimage',
            field=models.ImageField(default='default.png', upload_to='cover_pics'),
        ),
    ]
