# Generated by Django 3.1.6 on 2021-08-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_coverimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayname',
        ),
    ]
