# Generated by Django 3.1.6 on 2021-08-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210810_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(default='', max_length=25, verbose_name='Name'),
        ),
    ]
