# Generated by Django 3.0.5 on 2021-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coverimage',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
    ]
