# Generated by Django 3.0.5 on 2021-09-03 23:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210820_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverimage',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, verbose_name='coverimage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, verbose_name='image'),
        ),
    ]
