# Generated by Django 3.0.5 on 2021-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210904_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverimage',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='cover_pics'),
        ),
    ]
