# Generated by Django 3.1.6 on 2021-08-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='post_file',
        ),
    ]
