# Generated by Django 3.1.6 on 2021-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210811_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='default.png', upload_to='post_media'),
        ),
    ]
